### PR TITLE
Issue #63: Clarify the conditions in which consent for distinctive id…

### PR DESCRIPTION
**Pull request by mwatson2**
Clarify the conditions in which consent for distinctive identifiers is required.

Consent is required if the recommendations for clearing identifiers together with cookies etc. are not supported or if the user agent decides for other reasons that consent is required. Otherwise informing the user is a possible option per TAG guidance.

### CODE REVIEW

**Comment by mwatson2** [comment]
@ddorwin I have tried to address your comments.

I have two questions, though:
(1) We do not describe the persisting of user consent status. Should we, or should it be left to User Agents do decide whether and when to persist the consent status (perhaps based on a "do not ask me again" checkbox?).
(2) We do not have any "Denied" consent status, only ConsentRequired, InformUser and Allowed. That is, we can't persist the "Denied" status. Should UAs be allowed to persist a "Denied" status or are they required always to ask again ?

**Comment by ddorwin** [comment]
It looks like the rebase or some other action removed my comments from this PR and made them unreachable. For the record, they are at https://github.com/mwatson2/encrypted-media/commit/0d33734864311d6c61ad0f1af3f2213fd0611e39.

**Comment by ddorwin** [comment]
Replies to @mwatson2's questions:
(1) Good point. I think it's up to the UAs under what conditions to persist. However, it probably makes sense to mention that this MAY happen after the request. Thus, something simple like:
> The user agent MAY choose to persist the user response.

(2) Another good point. I believe UAs do persist denials for permissions. Chrome does, at least. The algorithms should allow that, though it is not required for UAs to implement it. I think we can address this by duplicating step 1 of Get Distinctive Identifier Consent Status and changing the new step 1 to "persisted denial" or "persisted blocking" and returning Denied.

Another minor item:
(3) I think we should add something like "and wait for the user response" to the end of the "Request user consent" step.

Other than the two comments above and these issues, this LG. Thanks!

**Comment by mwatson2** [comment]
Hmm, that would probably be the rebase, as it required a push --force to put up the new commits. I guess the alternative is not to rebase but to merge and then only do the rebase before finally merging the pull request ?

**Comment by ddorwin** [comment]
Hmm, probably. I guess we'll learn how to use the tool eventually. In the meantime, it's probably a good practice to save the commit URL before doing any forced push in case we need to manually post a comment pointing to it.

**Comment by mwatson2** [comment]
I believe this is ready to merge now. Any further comments from anyone ?

**Comment by ddorwin** [comment]
A few more minor comments. Also, see my first two comments above from yesterday. Each is for a separate commit. (GitHub doesn't appear to allow commenting on lines that weren't modified by a commit.)

**Comment by mwatson2** [comment]
Merged as 081f5696bd8315745d3bca29e92712613219e895

**Pull request closed without merging**
