### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by dret**

### CODE REVIEW

**Comment by jdsmith3000** [comment]
@dret These typo fixes look valid, but appear to have been made directly in index.html.  They should be made in encrypted-media-respec.html and then index.html is taken as a snapshot from it.  This is done under the "ReSpec" button in the top right of the document.  Are you able to update your PR for this?

**Comment by jdsmith3000** [comment]
To be clear, the commit should include both the encrypted-media-respec.html and index.html files.

**Comment by dret** [comment]
On 2016-04-26 16:16, jdsmith3000 wrote:
> To be clear, the commit should include both the
> encrypted-media-respec.html and index.html files.

done (i think).

**Comment by jdsmith3000** [comment]
Merged as https://github.com/w3c/encrypted-media/commit/8ef04d7.

**Comment by dret** [comment]
thanks.

**Pull request merged**
