### PR TITLE
Update editorship

### PR DESCRIPTION
**Pull request by joeyparrish**
- Add myself and Greg Freedman
 - Move David Dorwin, Jerry Smith, and Mark Watson to emeritus status

***
<a href="https://pr-preview.s3.amazonaws.com/joeyparrish/encrypted-media/pull/455.html" title="Last updated on Sep 26, 2019, 4:47 PM UTC (190088a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/encrypted-media/455/987b41e...joeyparrish:190088a.html" title="Last updated on Sep 26, 2019, 4:47 PM UTC (190088a)">Diff</a>

### CODE REVIEW

**Comment by joeyparrish** [comment]
@mwatson2, are you still going to be representing Netflix on EME?  Is there anyone else I should add?

**Comment by mwatson2** [comment]
You should replace me with Greg Freedman, gregwf@netflix.com

**Comment by joeyparrish** [comment]
Done.  Thanks!

**Comment by joeyparrish** [comment]
@plehegar, when you get time, could you take a look?  Thanks!

**Comment by tidoust** [comment]
Respec has a [`formerEditors` property](https://github.com/w3c/respec/wiki/formerEditors) that could be used instead of `note` to split the list between current editors and former ones. See the [Payment Request API](https://w3c.github.io/payment-request/) for an example. That's totally up to you though, notes are fine.

Side note that @plehegar will probably only follow discussions in this group from a distance or when needed (e.g. to track progress along the Recommendation track) from now on.

**Comment by tidoust** [comment]
@joeyparrish Note you should now have write rights to the repository (and should in particular be able to merge this and other pull requests)

**Comment by joeyparrish** [comment]
Done.  Thanks!

**Pull request merged**
