### PR TITLE
Issue #2 - Updated diagram with latest methods

### PR DESCRIPTION
**Pull request by steelejoe**
Updating stack-overview diagram to reflect latest methods

### CODE REVIEW

**Comment by ddorwin** [comment]
Thanks. LG except for some visual issues and nits. Please also change the commit message to be "Fix #2: Update the figure" or something like that. The important part is "Fix #2:"

Unless otherwise noted, these issues appear in both Chrome and Firefox.
* In Firefox, text is no longer centered. Examples: CDN, Net, MediaKeySession, CDM. Also, Media Stack runs into the first MediaKeySession.
* The first MediaKeySession is not centered even in Chrome. In Firefox, it extends outside its box.
* The font changed. The main problem is that the italics text looks bad, especially the e's.
* The MediaKeySession boxes appear to be at an angle. When scaled up, the horizontal lines are not straight.
* The optional (right) update arrow still has a weird double head.
* Please make the heads of the left update() arrow and the top (up) Frame arrow touch their target objects.

**Comment by ddorwin** [comment]
* The MediaKeySession boxes are different sizes. I think the right one can be trimmed on the right.

**Comment by steelejoe** [comment]
I think this has everything you wanted. You are correct the fonts changed, because the original SVG (as far as I can tell) used outlining which look snice but does not preserver font information. So I made a best guess. I believe the wonky arrows heads should all be corrected as well.

**Comment by ddorwin** [comment]
LGTM. Thanks!

Is there a reason the title was changed back? Perhaps when you force pushed the new commit, replacing the previous one?

There are a couple minor issues, but we can fix those in a separate PR if you want:
* The MediaKeySession boxes appear to be at an angle. When scaled up, the horizontal lines are not straight. This is more pronounced in Chrome that in Firefox.
* The `Frame` up arrow appears to have a double head.

**Comment by steelejoe** [comment]
The title change was likely the force commit. I am not seeing the slant you are seeing on Chrome or Firefox, but I will test on other platforms. Let me put together another PR.

**Comment by ddorwin** [comment]
I can't perceive see a slant, but the horizontal lines are not solid as if they are at an angle. Like `~~~----___` but more subtle. This is more obvious at high resolutions.

**Comment by ddorwin** [comment]
@steelejoe, what do you want to do? Shall we commit this and continue to fix minor details later?

**Comment by ddorwin** [comment]
@steelejoe, should we land this and make improvements later?

**Comment by steelejoe** [comment]
Sorry was looking into the wrong place for updates.  Yes please. Let's
commit this and I will work on correcting the slant after.

**Comment by ddorwin** [comment]
Merged as 336e7bd. Thank you!

**Pull request closed without merging**
