### PR TITLE
Fix #220: Remove deprecated support for insecure contexts

### LINKED ISSUE #220: Resolve question of support for insecure contexts
At the April 2015 face-to-face, we decided to mark support for insecure contexts as DEPRECATED and reevaluate support during CR. There is a Note to this effect in the [`requestMediaKeySystemAccess()` algorithm](https://w3c.github.io/encrypted-media/#requestMediaKeySystemAccess). We either need to remove the `Allowed` step and Note or otherwise update the Note before PR.

### PR DESCRIPTION
**Pull request by ddorwin**
Also updated text related to use of the APIs on insecure contexts.

The algorithm step is replaced with the `[SecureContext]` IDL attribute as discussed in #269.

### CODE REVIEW

**Comment by joeyparrish** [comment]
On what timeline will Chrome start enforcing secure origin?  When the info is available, I'd like to announce to the shaka-player-users list the date or Chrome release where this will happen.

**Comment by ddorwin** [comment]
@joeyparrish: Support on insecure contexts has been deprecated in Chrome for over a year, and we have seen content providers switching to HTTPS. While we have not yet given a timeline for enforcement, I expect that to happen soon, and we will clearly communicate this in Chrome and via other channels. We believe this spec change is an important step in presenting a consistent message - and eventually behavior - to authors as well as implementers.

**Comment by steelejoe** [comment]
Changes look good.

**Comment by mwatson2** [comment]
Looks good to me.

**Pull request merged**
