### PR TITLE
Use undefined union for MediaKeyStatusMap#get()

### PR DESCRIPTION
**Pull request by saschanaz**
Thanks to https://github.com/heycam/webidl/pull/906.

***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/encrypted-media/pull/477.html" title="Last updated on Dec 21, 2020, 3:12 PM UTC (606eb6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/encrypted-media/477/063addd...saschanaz:606eb6a.html" title="Last updated on Dec 21, 2020, 3:12 PM UTC (606eb6a)">Diff</a>

### CODE REVIEW

**Comment by joeyparrish** [comment]
It was hard to find the functional change among all the cosmetic changes, but the change looks good to me.  In the future, could you separate functional and cosmetic changes to make it easier to read the diff?

**Comment by saschanaz** [comment]
@joeyparrish Sorry to make the review hard, but fortunately there is "Hide whitespace changes" feature in GitHub for you 😉

image

**Comment by joeyparrish** [comment]
That's useful, but GitHub is by no means the only way we look at diffs in a repo's history.  I appreciate the whitespace cleanup, but I just prefer to have cosmetic commits separate from functional ones for clarity.  That was a community rule on [the first OSS project I ever contributed to](https://mplayerhq.hu/), and it still feels valuable to me after all these years.  Or maybe I'm just getting old.  :-)

**Comment by saschanaz** [comment]
Got it, I'll make sure to separate them next time 🙏

BTW I forgot to update the index.html here, should I open a new PR?

**Comment by joeyparrish** [comment]
After #479 is merged, nobody will ever have to manually regenerate index.html ever again.  🎉 🥳 🎈

**Pull request merged**
